### ISSUE TITLE
ToolsQA article on Git

### ISSUE THREAD

**Issue by firasm** [SheekhaJ/SheekhaJ.github.io#1]
Hello @SheekhaJ ! Hope you're doing well - I just wanted to check if you were the author of this ToolsQA tutorial: https://www.toolsqa.com/git/git-life-cycle/ 

I am looking for some supplemental material for my Data Science class and I'd like to link to your tutorial, and also potentially use some of your images during my class (with full attribution of course), and I didn't see an attribution or license to the content so I thought I'd check.

Please do let me know!

Cheers,

Firas 

Firas Moosvi (He/Him/His)
Lecturer
Department of Computer Science, Mathematics, Physics, and Statistics
The University of British Columbia | UBC Okanagan | Syilx Okanagan Nation Territory
3333 University Way | Kelowna BC | V1V 1V7 Canada

**Comment by SheekhaJ** [comment]
Hi Firas, 

Thanks and appreciate you reaching out. 
I'd written that article years back and it seems that it's been adapted a bit since then. I'm okay with you using the link to the tutorial. However, I'd recommend checking with [Lakshay Sharma](https://www.linkedin.com/in/lakshay-sharma-a4216312/) and [Virender Singh](https://www.linkedin.com/in/virender-singh-49312416/). 

Best, 
Sheekha
